name: Push to Codeberg proclub-scoop mirror

on:
  push:
  workflow_run:
    workflows: ["Collect & Compile Rule Sets"]
    types:
      - completed

jobs:
  codeberg-mirror:
    runs-on: ubuntu-latest
    # This ensures the mirror only attempts to push if it was triggered by a standard push
    # OR if the automated commit workflow finished successfully.
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          # Fetches full history so the push to Codeberg is seamless
          fetch-depth: 0

      - name: Push Commits to Codeberg
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts

          echo "${{ secrets.CODEBERG_SSH_KEY }}" > ~/.ssh/codeberg_key
          chmod 600 ~/.ssh/codeberg_key

          git remote add codeberg ${{ secrets.CODEBERG_REPO }}

          # Force push all branches to the mirror using our private key
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/codeberg_key"
          git push codeberg --all --force
